CREATE TABLE HOSPITAL.PHYSIO_USERDETAILS
(
  Id        INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 CYCLE ORDER KEEP) NOT NULL,
  UserName  NVARCHAR2(100)                      NOT NULL,
  Email     NVARCHAR2(255),
  Password  NVARCHAR2(255),
  Status    INTEGER
);


ALTER TABLE HOSPITAL.PHYSIO_USERDETAILS ADD (
  CONSTRAINT Physio_UserDetail_PK
  PRIMARY KEY
  (Id)
  ENABLE VALIDATE);
