CREATE TABLE HOSPITAL.PHYSIO_BODYIMAGES
(
  ID           INTEGER GENERATED ALWAYS AS IDENTITY (START WITH 1 INCREMENT BY 1 MINVALUE 1 MAXVALUE 9999999999999999999999999999 CACHE 20 CYCLE ORDER KEEP) NOT NULL,
  BODYPART     NVARCHAR2(255)                   NOT NULL,
  DESCRIPTION  NVARCHAR2(512),
  CREATEDBY    INTEGER,
  STATUS       INTEGER,
  IMAGEDATA    BLOB                             NOT NULL,
  FormatType  NVARCHAR2(50)
);


ALTER TABLE HOSPITAL.PHYSIO_BODYIMAGES ADD (
  CONSTRAINT PHYSIO_BODYIMAGES_PK
  PRIMARY KEY
  (ID)
  ENABLE VALIDATE);
